### ISSUE TITLE
Awesome Stuff

### ISSUE THREAD

**Issue by celestialmachines** [gh123man/Android-UIM#1]
Hi gh123man

This is awesome stuff that you are doing. I encourage you to continue with this work.

Also would you convert this into a library? Also please provide clarification on license used.

Perhaps you can have a look at for more inspiration: https://github.com/Avocarrot/json2view

Best Regards

Robert N

**Comment by gh123man** [comment]
Robert,

Thanks for the feedback. 
- I would make it a library once more views are supported. For now it can be included as a project module. 
- The license can be found in LICENSE.md at the project root.
- I have already looked into json2view. I stared this project to achieve a similar feature set but more closely match androids XML format though json as well as provide better event handling. 
- Currently the project is back burnered, I hope to come back to it once find more time.

**Comment by celestialmachines** [comment]
Hi gh123man

Thanks for the update. I'll be starring this project. And I am going to experiment with this, may I'd be able to use this in a future app.
- Thanks for the license info
- Closely matching android XML is what I was looking for. Perfect.

++ Another idea would be the ability to directly accept XML also and internally converted to JSON for those who need to use standard android XML in assets instead of JSON / Rest responses. 

---

If you are interested to know (else ignore this section), here is some background on how I hit upon UIM and what I plan to do with it:

So far in my R&D to make apps the easiest way, I have managed to write a demo app that is coded in multiple languages:

Kotlin, Xtend, Groovy, LuaJ, Processing, Beanshell, Scala , Javascript (via Rhino)

Along with some libraries such as anko, makroid, json2view... The final Apk is around 2.5MB only after proguard!

I personally feel that json2view has too many short comings, thats how I hit upon UIM. Will try to integrate UIM into that demo app and see how it would compare to json2view.

So far my finding is that that easiest way to write code is to make use of Kotlin, having rhino or beanshell or lua also is nice if you need some scripting and extensiblity ie download scripts from server w/o going through the app update cycle. If UIM becomes mature, the winning combination would be Kotlin (anko) + Beanshell + UIM.

Meanwhile I am on the look for a good pure java dbs for android... evaluating them soon, I believe that mapdb seems to be the better one.
